version: "3"
services:
  http-server:
    build:
      context: ./service/
      dockerfile: dockerfile
    environment:
      HTTP_HOST: "0.0.0.0"
      HTTP_PORT: "8080"

  http-server1:
    build:
      context: ./service/
      dockerfile: dockerfile
    environment:
      HTTP_HOST: "0.0.0.0"
      HTTP_PORT: "8081"
      HTTP_ROUTE: "/api1"

  http-server2:
    build:
      context: ./service/
      dockerfile: dockerfile
    environment:
      HTTP_HOST: "0.0.0.0"
      HTTP_PORT: "8082"
      HTTP_ROUTE: "/api2"

  nginx-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - http-server
